services:
  php:
    depends_on:
      - database
    build:
      context: .
      dockerfile: Dockerfile
    image: chatapp
    container_name: chatapp
    ports:
      - "9000:9000" # Port for frontend
      - "8000:8000" # Port for backend
    networks:
      - chatapp

  database:
    image: mysql:latest
    restart: unless-stopped
    container_name: database
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    networks:
      - chatapp

volumes:
  db-data:
networks:
  chatapp:
    driver: bridge
